---
title: "Temp: "
author: | 
  | Dan Xu
  | University of Toronto
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    toc: false
bibliography: references.bib
abstract: |
  This project is a replication for "[Digital literacy is associated with more discerning accuracy judgments but not sharing intentions](https://misinforeview.hks.harvard.edu/article/digital-literacy-is-associated-with-more-discerning-accuracy-judgments-but-not-sharing-intentions/)". Through a survey experiment with a sample of 4,283 U.S. respondents, @grinberg2019fake find that voter fraud misinformation reduces public confidence in electoral integrity. I performed Ordinary Least-squares regression analyses to replicate their research, and my results show consistency with their findings. However, I also find that voter fraud misinformation increases public confidence in elections if one identifies as a Democrat, suggesting a potential "backfire effect" among partisans when they are constantly exposed to counter-belief fact-checked evidence.   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load data
# rm(list = ls())

load("data/covid.Rda")
load("data/political.Rda")

```


```{r}
covid <- to_merge
political <- to_mergeCOVID
# merge them
data <- rbind(covid, political)
# construct FB newsfeed digital literacy variable
#     if people said dont know on first response, use their second response
data[!is.na(data$FbDec_1),]$FbDec <- data[!is.na(data$FbDec_1),]$FbDec_1
data$diglit2 <- data$FbDec==4
```


```{r}
data
```

# Introduction 

Misinformation has been exacerbating the public trust in political and societal institutions. It is widely assumed that a lack of digital literacy - an individual's ability to fluently use digital technology to assess the veracity of information, may lead to higher susceptibility to fake news and misinformation. 



```{r}

### 
# Accuracy discernment

# each variable separately
acc_model_diglit <- lm(scale(acc_discernment)~(scale(diglit)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(acc_model_diglit)
acc_model_diglit2 <- lm(scale(acc_discernment)~(scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(acc_model_diglit2)
acc_model_crt <- lm(scale(acc_discernment)~(scale(crt)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(acc_model_crt)
acc_model_newsknow <- lm(scale(acc_discernment)~(scale(newsknow)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(acc_model_newsknow)

# all together
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C)*scale(political),data=data)
summary(acc_model)
#
# decomposing to look at interactions
#
# dem
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C<4)   ,])
summary(acc_model)
# rep 
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C>3)   ,])
summary(acc_model)
# covid
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==0)  ,])
summary(acc_model)
# politics
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==1)  ,])
summary(acc_model)
#
# dem covid
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==0)  ,])
summary(acc_model)
# dem politics
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==1)  ,])
summary(acc_model)
# rep covid
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==0)  ,])
summary(acc_model)
# rep politics
acc_model <- lm(scale(acc_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==1)  ,])
summary(acc_model)







### 
# Sharing  discernment

# each variable separately
sharing_model_diglit <- lm(scale(sharing_discernment)~(scale(diglit)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing_model_diglit)
sharing_model_diglit2 <- lm(scale(sharing_discernment)~(scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing_model_diglit2)
sharing_model_crt <- lm(scale(sharing_discernment)~(scale(crt)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing_model_crt)
sharing_model_newsknow <- lm(scale(sharing_discernment)~(scale(newsknow)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing_model_newsknow)

# All together
sharing_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C)*scale(political),data=data)
summary(sharing_model)
#
# decomposing to look at interactions
# dem
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C<4)   ,])
summary(s_model)
# rep 
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C>3)   ,])
summary(s_model)
# covid
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==0)  ,])
summary(s_model)
# politics
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==1)  ,])
summary(s_model)
#
#
# dem covid
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==0)  ,])
summary(s_model)
# dem politics
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==1)  ,])
summary(s_model)
# rep covid
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==0)  ,])
summary(s_model)
# rep politics
s_model <- lm(scale(sharing_discernment)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==1)  ,])
summary(s_model)
```

```{r eval=FALSE}
####
# Fraction of shared news that is true

# each variable separately
sharing2_model_diglit <- lm(scale(sharing_discernment2)~(scale(diglit)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing2_diglit)
sharing2_model_diglit2 <- lm(scale(sharing_discernment2)~(scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing2_diglit2)
sharing2_model_crt <- lm(scale(sharing_discernment2)~(scale(crt)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing2_model_crt)
sharing2_model_newsknow <- lm(scale(sharing_discernment2)~(scale(newsknow)+scale(college)+scale(age)+scale(female)+scale(white))+scale(DemRep_C)+scale(political),data=data)
summary(sharing2_model_newsknow)

# all together
sharing2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C)*scale(political),data=data)
summary(sharing2_model)
#
# decomposing to see interactions
# dem
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C<4)   ,])
summary(s2_model)
# rep 
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(political),data=data[(data$DemRep_C>3)   ,])
summary(s2_model)
# covid
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==0)  ,])
summary(s2_model)
# politics
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white))*scale(DemRep_C),data=data[ (data$political==1)  ,])
summary(s2_model)
#
#
# dem covid
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==0)  ,])
summary(s2_model)
# dem politics
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C<4) & (data$political==1)  ,])
summary(s2_model)
# rep covid
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==0)  ,])
summary(s2_model)
# rep politics
s2_model <- lm(scale(sharing_discernment2)~(scale(crt)+scale(newsknow)+scale(diglit)+scale(diglit2)+scale(college)+scale(age)+scale(female)+scale(white)),data=data[(data$DemRep_C>3) & (data$political==1)  ,])
summary(s2_model)
```


## R Markdown

cross-referening 


